// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMIvew_MNdGyYWeK0FlHOlqQSTee6MeU',
    appId: '1:845897869656:web:6faa60ed29c03b032b1d2d',
    messagingSenderId: '845897869656',
    projectId: 'sumeeb-chat',
    authDomain: 'sumeeb-chat.firebaseapp.com',
    storageBucket: 'sumeeb-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC8ZitV3mM_sWrRrwoBR9Fyw7db7HbUKk',
    appId: '1:845897869656:android:201c998036b62eda2b1d2d',
    messagingSenderId: '845897869656',
    projectId: 'sumeeb-chat',
    storageBucket: 'sumeeb-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuiZPHtpD2VjI2E-efrXjeNgGvElqtO30',
    appId: '1:845897869656:ios:cefe741e0e6a9e9f2b1d2d',
    messagingSenderId: '845897869656',
    projectId: 'sumeeb-chat',
    storageBucket: 'sumeeb-chat.firebasestorage.app',
    iosBundleId: 'com.sumeeb.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCMIvew_MNdGyYWeK0FlHOlqQSTee6MeU',
    appId: '1:845897869656:web:560abea7ba3623282b1d2d',
    messagingSenderId: '845897869656',
    projectId: 'sumeeb-chat',
    authDomain: 'sumeeb-chat.firebaseapp.com',
    storageBucket: 'sumeeb-chat.firebasestorage.app',
  );
}
