name: Flutter Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7" # Change to your version

      # Enable Windows Desktop
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      # Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # Build Windows app
      - name: Build Windows
        run: flutter build windows --release

      # Upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release
