name: Flutter Build (Windows + Android)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # Windows for desktop, Ubuntu for Android
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7" # Change to your version

      # Enable Windows Desktop only on Windows
      - name: Enable Windows Desktop
        if: matrix.os == 'windows-latest'
        run: flutter config --enable-windows-desktop

      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Build APK (on Ubuntu)
      - name: Extract Version from pubspec.yaml
        if: matrix.os == 'ubuntu-latest'
        id: get_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f2 | cut -d '+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build Android APK
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      # Build Windows exe (on Windows)
      - name: Build Windows exe
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release

      # Upload artifacts
      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release

      - name: Upload Android Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./release/windows

      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: ./release/android

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          draft: false
          prerelease: false
          files: |
            ./release/android/app-release.apk
            ./release/windows/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
